apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rusun-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /adm(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: s-rusun-adm
            port:
              number: 3001

      - path: /app(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: s-rusun-app
            port:
              number: 3002
