apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-rusun-adm
  labels:
    app: s-rusun-adm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-rusun-adm
  template:
    metadata:
      labels:
        app: s-rusun-adm
    spec:
      containers:
        - name: s-rusun-adm
          image: image: ghcr.io/wilsonn06/s-rusun-ui:sha-initial
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
