apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-rusun-app
  labels:
    app: s-rusun-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-rusun-app
  template:
    metadata:
      labels:
        app: s-rusun-app
    spec:
      containers:
        - name: s-rusun-app
          image: ghcr.io/wilsonn06/s-rusun-app:sha-082b268
          ports:
            - containerPort: 3002
          imagePullPolicy: Always
          env:
            - name: ADMIN_URL
              value: "http://s-rusun-adm:3001"
