apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-rusun-adm
  labels:
    app: s-rusun-adm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-rusun-adm
  template:
    metadata:
      labels:
        app: s-rusun-adm
    spec:
      containers:
        - name: s-rusun-adm
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"