apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-rusun-adm
  labels:
    app: s-rusun-adm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-rusun-adm
  template:
    metadata:
      labels:
        app: s-rusun-adm
    spec:
      containers:
      - name: s-rusun-adm
        image: wilsonnn06/s-rusun-addm:latest   # ‚Üê image DockerHub Anda
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "mysql.srusun.id"
        - name: DB_USER
          value: "wilson"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: rusun-db-secret
              key: password
        - name: DB_NAME
          value: "payment"
