apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-rusun-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-rusun-app
  template:
    metadata:
      labels:
        app: s-rusun-app
    spec:
      containers:
        - name: s-rusun-app
          image: asia-southeast2-docker.pkg.dev/steady-cascade-479108-s5/rusun-repo/s-rusun-app:sha-2bbf6fe
          ports:
            - containerPort: 3002
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
