apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rusun-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /adm
        pathType: Prefix
        backend:
          service:
            name: s-rusun-adm
            port:
              number: 3001
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: s-rusun-app
            port:
              number: 3002
      - path: /
        pathType: Prefix
        backend:
          service:
            name: s-rusun-ui
            port:
              number: 80
