apiVersion: v1
kind: Secret
metadata:
  name: kong-secrets
  namespace: kong
type: Opaque
stringData:
  KONG_PASSWORD: "handyshake"
  KONG_PG_PASSWORD: "kong"        # samakan dengan yang kamu pakai sebelumnya (docker-compose)
  KONG_LICENSE_DATA: "<PASTE_YOUR_KONG_LICENSE_DATA_HERE>"
