apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-rusun-adm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-rusun-adm
  template:
    metadata:
      labels:
        app: s-rusun-adm
    spec:
      containers:
        - name: s-rusun-adm
          image: asia-southeast2-docker.pkg.dev/steady-cascade-479108-s5/rusun-repo/s-rusun-adm:sha-a1345d9
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
